### ISSUE TITLE
Rebuild against libxml Version 2.9.4

### ISSUE THREAD

**Issue by Jan-E** [winlibs/libxslt#1]
@weltling PHP 7.1 Alpha now shows:

>libxslt compiled against libxml Version	2.9.2

I did not check for older PHP versions, but it seems better to rebuild it against 2.9.4

**Comment by weltling** [comment]
Done while upgrading to 1.1.29. Thanks for the ping.

**Comment by Jan-E** [comment]
I see the PHP 5.6 snapshots are stll using an old version:
```
XSL	enabled
libxslt Version	1.1.27
libxslt compiled against libxml Version	2.7.8
EXSLT	enabled
libexslt Version	0.8.16
```
If I use the new deps like http://windows.php.net/downloads/php-sdk/deps/vc11/x64/libxslt-1.1.29-vc11-x64.zip I am running into unresolved external symbols xmlBufUse and xmlBufContent. This is a nasty thing. I never got any further than building (and linking) libxslt compiled against libxml version 2.8.0 (VC9 & VC11). 

There is some conflict along these lines:
https://github.com/winlibs/libxslt/blob/master/libxslt/xsltutils.c#L1774
https://github.com/winlibs/libxml2/blob/master/buf.c

**Comment by weltling** [comment]
Thanks for checking. PHP5 needs additional adjustment which is done in the dev branches already. We need 1.1.29 for a CVE fix, and it is cleaner to have a dep upgrade instead of patching some older lib. The latest dev branch links fine with the current deps. At least 5.5 should get this because it's the last release.

Thanks.

**Comment by Jan-E** [comment]
> PHP5 needs additional adjustment which is done in the dev branches already.

Could you tell me where I can find these adjustments?

I managed to add xmlBufUse and xmlBufContent to libxslt_a.lib in an ugly way: compiling the buf.c/h of linxml2 2.9.4 into libxslt as well. But I had to remove __xmlSimpleError in buf.c, because that also gave an unresolved external while compiling libxslt.

**Comment by weltling** [comment]
Hi Jan,

take a look at ext/libxml/php_libxml.def.

Thanks.

**Comment by Jan-E** [comment]
> take a look at ext/libxml/php_libxml.def

A, thanks. I see you have already backported this to PHP 5.5 & 5.6: https://github.com/php/php-src/commit/fe1d6feb3dfa1eebd69a82c8000d2095b4e8a531

**Comment by Jan-E** [comment]
I did not test it yet, but would not it be a more portable solution do do the export in
https://github.com/winlibs/libxml2/blob/master/win32/libxml2.def.src

Something like adding
```
#include "../include/libxml/tree.h"
#ifdef LIBXML2_NEW_BUFFER
xmlBufUse
xmlBufContent
#endif
```
Then other users like @mhils in https://github.com/winlibs/libxslt/issues/2 would have the benefit as well.
