### ISSUE TITLE
Upgrade to libxslt-1.1.29 / Fix VS2015 compat

### ISSUE THREAD

**Issue by mhils** [winlibs/libxslt#2]
When building lxml for Python 3.5, I needed to adjust libxslt's `win32config.h` to account for the newly added `snprintf` support. Turns out, this has already been adressed upstream and libxslt-1.1.29 fixes compatiblity with VS2015: https://git.gnome.org/browse/libxslt/commit/libxslt/win32config.h?id=e75b5da121cdc67cb2303b1e2b77d5dd1cdf2784

Long story short, to support VS2015 the code should be updated to libxslt 1.1.29!

I could not really figure out which entity is behind the winlibs org here (PHP?), 
but THANK YOU SO MUCH. :smiley:

**Comment by weltling** [comment]
Just did the upgrade, the builds are here http://windows.php.net/downloads/php-sdk/deps/vc14/. I most likely forgot to push the change in the header for 1.1.28 :(

Yeah, winlibs are deps for PHP, but really joyful other projects profit as well :)

Thanks!
