### ISSUE TITLE
Update to libxslt 1.1.39

### ISSUE THREAD

**Issue by cmb69** [winlibs/libxslt#7]
I've just noticed that @nielsdos commited an update to libxslt 1.1.39 eight months ago, but apparently that had never been rolled out. Has there been any particular reason?

**Comment by ndossche** [comment]
Because Derick didn't want to upload the zips.

**Comment by cmb69** [comment]
Ah, the automatic uploads… If mankind had waited for automatic cars, we wouldn't even have wheels.

Anyway, do you think it makes sense to roll out 1.1.39, or should we update to 1.1.42 right away?

**Comment by ndossche** [comment]
The only thing that concerns me a bit is https://github.com/GNOME/libxslt/blob/5df99903aef143d605be69cbd4fbf246871cd113/NEWS#L71 as I'm not sure what the impact would be. See also https://gitlab.gnome.org/GNOME/libxml2/-/issues/753 for an issue I had with that in libxml2.
I didn't test 1.1.42, but if it would work then it sure makes sense to bump to that.

**Comment by cmb69** [comment]
For time reasons, I [went with 1.1.39 for now](https://github.com/winlibs/winlib-builder/issues/23#issuecomment-2446769046). We can still backport, and do further updates later. I'll try to keep an eye on 1.1.42.
